// Production Configuration for Backend
export const PRODUCTION_CONFIG = {
  // Server Configuration
  PORT: process.env.PORT || 5000,
  NODE_ENV: 'production',
  
  // Database Configuration
  MONGODB_URI: process.env.MONGODB_URI,
  
  // CORS Configuration
  CORS_ORIGINS: [
    'https://thinqscribe.com',
    'https://www.thinqscribe.com',
    'http://localhost:5173' // For development
  ],
  
  // JWT Configuration
  JWT_SECRET: process.env.JWT_SECRET,
  JWT_EXPIRES_IN: '7d',
  
  // Stripe Configuration
  STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY,
  STRIPE_PUBLISHABLE_KEY: process.env.STRIPE_PUBLISHABLE_KEY,
  STRIPE_WEBHOOK_SECRET: process.env.STRIPE_WEBHOOK_SECRET,
  
  // Paystack Configuration
  PAYSTACK_SECRET_KEY: process.env.PAYSTACK_SECRET_KEY,
  PAYSTACK_PUBLIC_KEY: process.env.PAYSTACK_PUBLIC_KEY,
  PAYSTACK_WEBHOOK_SECRET: process.env.PAYSTACK_WEBHOOK_SECRET,
  
  // Email Configuration
  MAILTRAP_HOST: process.env.MAILTRAP_HOST,
  MAILTRAP_PORT: process.env.MAILTRAP_PORT,
  MAILTRAP_USER: process.env.MAILTRAP_USER,
  MAILTRAP_PASS: process.env.MAILTRAP_PASS,
  EMAIL_FROM: process.env.EMAIL_FROM,
  
  // Resend Email Configuration
  RESEND_API_KEY: process.env.RESEND_API_KEY,
  
  // Client URL
  CLIENT_URL: process.env.CLIENT_URL || 'https://thinqscribe.com',
  FRONTEND_URL: process.env.FRONTEND_URL || 'https://thinqscribe.com',
  
  // Session Configuration
  SESSION_SECRET: process.env.SESSION_SECRET,
  
  // AWS Configuration (if using S3)
  AWS_ACCESS_KEY_ID: process.env.AWS_ACCESS_KEY_ID,
  AWS_SECRET_ACCESS_KEY: process.env.AWS_SECRET_ACCESS_KEY,
  AWS_REGION: process.env.AWS_REGION || 'us-east-1',
  AWS_S3_BUCKET: process.env.AWS_S3_BUCKET,
  
  // API Keys
  SERP_API_KEY: process.env.SERP_API_KEY,
  NEWS_API_KEY: process.env.NEWS_API_KEY
};

// Environment variables for backend
export const BACKEND_ENV = {
  PORT: PRODUCTION_CONFIG.PORT,
  NODE_ENV: PRODUCTION_CONFIG.NODE_ENV,
  MONGODB_URI: PRODUCTION_CONFIG.MONGODB_URI,
  JWT_SECRET: PRODUCTION_CONFIG.JWT_SECRET,
  JWT_EXPIRES_IN: PRODUCTION_CONFIG.JWT_EXPIRES_IN,
  STRIPE_SECRET_KEY: PRODUCTION_CONFIG.STRIPE_SECRET_KEY,
  STRIPE_PUBLISHABLE_KEY: PRODUCTION_CONFIG.STRIPE_PUBLISHABLE_KEY,
  STRIPE_WEBHOOK_SECRET: PRODUCTION_CONFIG.STRIPE_WEBHOOK_SECRET,
  PAYSTACK_SECRET_KEY: PRODUCTION_CONFIG.PAYSTACK_SECRET_KEY,
  PAYSTACK_PUBLIC_KEY: PRODUCTION_CONFIG.PAYSTACK_PUBLIC_KEY,
  PAYSTACK_WEBHOOK_SECRET: PRODUCTION_CONFIG.PAYSTACK_WEBHOOK_SECRET,
  MAILTRAP_HOST: PRODUCTION_CONFIG.MAILTRAP_HOST,
  MAILTRAP_PORT: PRODUCTION_CONFIG.MAILTRAP_PORT,
  MAILTRAP_USER: PRODUCTION_CONFIG.MAILTRAP_USER,
  MAILTRAP_PASS: PRODUCTION_CONFIG.MAILTRAP_PASS,
  EMAIL_FROM: PRODUCTION_CONFIG.EMAIL_FROM,
  RESEND_API_KEY: PRODUCTION_CONFIG.RESEND_API_KEY,
  CLIENT_URL: PRODUCTION_CONFIG.CLIENT_URL,
  FRONTEND_URL: PRODUCTION_CONFIG.FRONTEND_URL,
  SESSION_SECRET: PRODUCTION_CONFIG.SESSION_SECRET,
  AWS_ACCESS_KEY_ID: PRODUCTION_CONFIG.AWS_ACCESS_KEY_ID,
  AWS_SECRET_ACCESS_KEY: PRODUCTION_CONFIG.AWS_SECRET_ACCESS_KEY,
  AWS_REGION: PRODUCTION_CONFIG.AWS_REGION,
  AWS_S3_BUCKET: PRODUCTION_CONFIG.AWS_S3_BUCKET,
  SERP_API_KEY: PRODUCTION_CONFIG.SERP_API_KEY,
  NEWS_API_KEY: PRODUCTION_CONFIG.NEWS_API_KEY
}; 
