services:
  - type: web
    name: thinqscribe-backend
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: PAYSTACK_SECRET_KEY
        sync: false
      - key: PAYSTACK_PUBLIC_KEY
        sync: false
      - key: PAYSTACK_WEBHOOK_SECRET
        sync: false
      - key: MAILTRAP_HOST
        sync: false
      - key: MAILTRAP_PORT
        sync: false
      - key: MAILTRAP_USER
        sync: false
      - key: MAILTRAP_PASS
        sync: false
      - key: EMAIL_FROM
        sync: false
      - key: CLIENT_URL
        value: https://thinqscribe.com
      - key: FRONTEND_URL
        value: https://thinqscribe.com
      - key: SESSION_SECRET
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_REGION
        sync: false
      - key: AWS_S3_BUCKET
        sync: false
      - key: SERP_API_KEY
        sync: false
      - key: NEWS_API_KEY
        sync: false
    healthCheckPath: /api/health
    autoDeploy: true
    branch: main 